# Generated by Django 3.0.8 on 2020-07-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200724_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='isUpdated',
            field=models.BooleanField(default=False),
        ),
    ]
