# Generated by Django 3.0.8 on 2020-07-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200724_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='lat_lng',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
