# Generated by Django 3.0.8 on 2020-07-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_lat_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='lat_lng',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
